"use client";

import React, { useRef, useState, useEffect } from 'react';
import { Canvas, useFrame } from '@react-three/fiber';
import { OrbitControls, Stars, Sphere, useTexture, shaderMaterial } from '@react-three/drei';
import * as THREE from 'three';
import { extend } from '@react-three/fiber';
import { useTelemetryStore } from '@/lib/memory/useTelemetryStore';

// ----------------------------------------------------
// Multi-Modal Terrain Shader (Simulates OHRC/TMC/IIRS)
// ----------------------------------------------------
const MultiModalMaterial = shaderMaterial(
  {
    uTime: 0,
    uTexture: new THREE.Texture(),
    uSunPosition: new THREE.Vector3(10, 5, 0),
    uMode: 0, // 0 = TMC (Base), 1 = OHRC (High Res), 2 = IIRS (Hyperspectral)
  },
  // Vertex Shader
  `
    varying vec2 vUv;
    varying vec3 vNormal;
    varying vec3 vViewPosition;
    varying vec3 vWorldPosition;
    uniform float uTime;

    void main() {
      vUv = uv;
      vNormal = normalize(normalMatrix * normal);
      vec4 mvPosition = modelViewMatrix * vec4(position, 1.0);
      vViewPosition = -mvPosition.xyz;
      
      vec4 worldPos = modelMatrix * vec4(position, 1.0);
      vWorldPosition = worldPos.xyz;
      
      gl_Position = projectionMatrix * mvPosition;
    }
  `,
  // Fragment Shader
  `
    varying vec2 vUv;
    varying vec3 vNormal;
    varying vec3 vViewPosition;
    varying vec3 vWorldPosition;
    
    uniform sampler2D uTexture;
    uniform float uTime;
    uniform vec3 uSunPosition;
    uniform int uMode;

    void main() {
      // Sample displacement map (grayscale) for crater depth
      vec4 texColor = texture2D(uTexture, vUv);
      float depth = texColor.r;

      // Compute Lighting (Sun Angle Simulation)
      vec3 normal = normalize(vNormal);
      vec3 lightDir = normalize(uSunPosition - vWorldPosition);
      float diffuse = max(dot(normal, lightDir), 0.0);
      
      // Simulate shadows based on depth and light direction
      float shadow = 1.0;
      if (depth < 0.3 && diffuse < 0.4) {
        shadow = 0.2; // Deep craters cast shadows at low sun angles
      }

      vec3 baseColor = vec3(0.5); // Moon gray
      
      if (uMode == 0) {
        // TMC Mode: Standard grayscale with shadows
        baseColor = vec3(depth * 0.8 + 0.2) * diffuse * shadow;
      } else if (uMode == 1) {
        // OHRC Mode: High contrast, high detail (simulated by tiling noise)
        float detail = fract(sin(dot(vUv * 100.0, vec2(12.9898, 78.233))) * 43758.5453);
        baseColor = vec3(depth) * diffuse * shadow + (detail * 0.1);
        // Highlight matched features
        if (fract(vUv.x * 20.0) < 0.05 && fract(vUv.y * 20.0) < 0.05) {
          baseColor = vec3(0.0, 1.0, 0.0); // Green tie-points
        }
      } else if (uMode == 2) {
        // IIRS Mode: Hyperspectral heat map based on depth
        vec3 color1 = vec3(0.0, 0.0, 1.0); // Blue
        vec3 color2 = vec3(1.0, 0.0, 0.0); // Red
        baseColor = mix(color1, color2, depth) * diffuse;
      }

      gl_FragColor = vec4(baseColor, 1.0);
    }
  `
);

extend({ MultiModalMaterial });

function MultiModalMoon({ sunAngle, mode, showMatches }: { sunAngle: number, mode: number, showMatches: boolean }) {
  const moonGroupRef = useRef<THREE.Group>(null);
  const materialRef = useRef<any>(null);
  const texture = useTexture('/moon_color.jpg');

  // Load matches generated by the backend
  const [matches, setMatches] = useState<any[]>([]);
  useEffect(() => {
    fetch('/matches.json')
      .then((res) => res.json())
      .then(setMatches)
      .catch(() => setMatches([]));
  }, []);

  useFrame(({ clock }) => {
    if (moonGroupRef.current) {
      moonGroupRef.current.rotation.y += 0.001; 
    }
    if (materialRef.current) {
      materialRef.current.uTime = clock.getElapsedTime();
      
      // Calculate sun position based on angle
      const radius = 10;
      const x = Math.cos(sunAngle) * radius;
      const y = Math.sin(sunAngle) * radius;
      materialRef.current.uSunPosition.set(x, y, 0);
      materialRef.current.uMode = mode;
    }
  });

  return (
    <group ref={moonGroupRef} rotation={[0.027, 0, 0]}>
      {/* Outer Shell using MultiModalMaterial */}
      <Sphere args={[1.5, 128, 128]} position={[0, 0, 0]}>
        {/* @ts-ignore - Dynamically extended element */}
        <multiModalMaterial 
          ref={materialRef} 
          uTexture={texture}
        />
      </Sphere>
      
      {showMatches && matches.length > 0 && (
        <MatchesLayer matches={matches} radius={1.51} />
      )}
    </group>
  );
}

function ScientificCameraController() {
  const cameraRef = useRef<any>(null);
  return (
    <OrbitControls ref={cameraRef} enableZoom={true} enablePan={true} autoRotate={false} maxDistance={10} minDistance={2} />
  );
}

export default function ScientificDigitalTwin() {
  const [sunAngle, setSunAngle] = useState(0.5); // Range 0 to PI
  const [mode, setMode] = useState(0); // 0: TMC, 1: OHRC, 2: IIRS
  const [showMatches, setShowMatches] = useState(true);

  // Automatically cycle modes for demonstration if not interacted
  useEffect(() => {
    const interval = setInterval(() => {
      setMode((prev) => (prev + 1) % 3);
    }, 5000);
    return () => clearInterval(interval);
  }, []);

  return (
    <div className="w-full h-full bg-[#000510] relative flex flex-col">
      {/* Controls Overlay */}
      <div className="absolute top-4 left-4 z-10 bg-black/80 p-5 rounded border border-cyan-800 flex flex-col gap-5 text-white shadow-[0_0_20px_rgba(0,255,255,0.2)] max-w-sm backdrop-blur-md">
        
        <div>
          <h2 className="text-sm font-bold text-cyan-400 mb-1 tracking-wider border-b border-cyan-900 pb-1">SIH26166: ILLUMINATION INVARIANCE</h2>
          <p className="text-[10px] text-slate-300 mb-3 leading-relaxed">
            Demonstrating scale & sun-angle invariant correspondence using LoFTR deep learning. Watch feature matching persist as shadows dynamically change.
          </p>
          <label className="block text-xs font-mono text-cyan-300 mb-1">DATA FUSION LAYER (SCALE)</label>
          <div className="flex gap-2">
            <button onClick={() => setMode(0)} className={`px-2 py-1 text-xs border ${mode === 0 ? 'bg-cyan-900 border-cyan-400 text-white' : 'border-slate-700 text-slate-400'}`}>TMC (5m)</button>
            <button onClick={() => setMode(1)} className={`px-2 py-1 text-xs border ${mode === 1 ? 'bg-cyan-900 border-cyan-400 text-white' : 'border-slate-700 text-slate-400'}`}>OHRC (0.25m)</button>
            <button onClick={() => setMode(2)} className={`px-2 py-1 text-xs border ${mode === 2 ? 'bg-cyan-900 border-cyan-400 text-white' : 'border-slate-700 text-slate-400'}`}>IIRS</button>
          </div>
        </div>
        
        <div>
          <div className="flex justify-between items-center mb-1">
            <label className="text-xs font-mono text-cyan-300">DYNAMIC SUN ANGLE</label>
            <span className="text-[10px] font-mono text-slate-400">{(sunAngle * 57.29).toFixed(1)}°</span>
          </div>
          <input 
            type="range" 
            min="0.1" 
            max="3.0" 
            step="0.1"
            value={sunAngle}
            onChange={(e) => setSunAngle(parseFloat(e.target.value))}
            className="w-full accent-cyan-500"
          />
        </div>

        <div className="flex items-center gap-2">
          <input 
            type="checkbox" 
            id="matches-toggle"
            checked={showMatches}
            onChange={(e) => setShowMatches(e.target.checked)}
            className="accent-cyan-500"
          />
          <label htmlFor="matches-toggle" className="text-xs font-mono text-cyan-300 cursor-pointer">
            OVERLAY DL CORRESPONDENCE POINTS
          </label>
        </div>
      </div>

      <div className="flex-1 relative">
        <Canvas camera={{ position: [0, 0, 5], fov: 45 }}>
          <color attach="background" args={['#000510']} />
          <Stars radius={50} depth={20} count={1000} factor={2} saturation={1} fade speed={0.5} />
          <React.Suspense fallback={null}>
            <MultiModalMoon sunAngle={sunAngle} mode={mode} showMatches={showMatches} />
          </React.Suspense>
          <ScientificCameraController />
        </Canvas>
        
        {/* HUD Grid Overlay */}
        <div className="absolute inset-0 pointer-events-none opacity-20" style={{
          backgroundImage: 'linear-gradient(#0ff 1px, transparent 1px), linear-gradient(90deg, #0ff 1px, transparent 1px)',
          backgroundSize: '40px 40px',
          boxShadow: 'inset 0 0 100px rgba(0,0,0,1)'
        }} />
      </div>
    </div>
  );
}
function MatchesLayer({ matches, radius }: { matches: any[]; radius: number }) {
  // Convert UV coordinates from matches (using 256 as proxy scale) to 3D positions
  return (
    <group>
      {matches.slice(0, 150).map((m, i) => {
        // Map x,y to spherical coordinates
        const u = (m.img1_x % 256) / 256;
        const v = (m.img1_y % 256) / 256;
        
        // Slightly cluster them on the front face for visibility
        const theta = (v * Math.PI) / 2 + Math.PI / 4; 
        const phi = (u * Math.PI) / 2 - Math.PI / 4; 
        
        const x = radius * Math.sin(theta) * Math.cos(phi);
        const y = radius * Math.cos(theta);
        const z = radius * Math.sin(theta) * Math.sin(phi);
        
        return (
          <group key={i} position={[x, y, z]}>
            <mesh>
              <sphereGeometry args={[0.015, 8, 8]} />
              <meshBasicMaterial color="#00ffaa" />
            </mesh>
            {/* Draw a subtle line shooting out to represent correspondence */}
            <mesh position={[0, 0, 0.05]}>
               <cylinderGeometry args={[0.002, 0.002, 0.1]} />
               <meshBasicMaterial color="#00ffaa" transparent opacity={0.5} />
            </mesh>
          </group>
        );
      })}
    </group>
  );
}
